# Generated by Django 4.0.4 on 2022-04-21 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='name6',
            field=models.UUIDField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='name5',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='cont',
            fields=[
                ('demo', models.BigAutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50, unique=True)),
                ('id1', models.CharField(max_length=50, null=True)),
                ('id2', models.CharField(default='value', max_length=50)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.sample')),
            ],
        ),
    ]
