# Generated by Django 4.0.4 on 2022-04-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='text',
        ),
    ]
