# Generated by Django 4.0.4 on 2022-04-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='age',
        ),
    ]
