# Generated by Django 4.0.4 on 2022-04-22 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='nontech',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hier.base')),
                ('design', models.CharField(max_length=40)),
                ('sal', models.IntegerField()),
            ],
            bases=('hier.base',),
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hier.base')),
                ('course', models.CharField(max_length=40)),
                ('batch', models.CharField(max_length=40)),
                ('fee', models.IntegerField()),
            ],
            bases=('hier.base',),
        ),
        migrations.CreateModel(
            name='tech',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hier.base')),
                ('design', models.CharField(max_length=40)),
                ('sub', models.CharField(max_length=40)),
                ('sal', models.IntegerField()),
            ],
            bases=('hier.base',),
        ),
    ]
