# Generated by Django 4.0.4 on 2022-04-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sal', models.IntegerField()),
                ('dept', models.CharField(max_length=25)),
                ('mtr', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='proxyemployee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('prox.employee',),
        ),
    ]
