# Generated by Django 4.0.4 on 2022-04-22 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='bank1',
            fields=[
                ('bank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mlevel.bank')),
                ('pan', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
            ],
            bases=('mlevel.bank',),
        ),
        migrations.CreateModel(
            name='bank2',
            fields=[
                ('bank1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mlevel.bank1')),
                ('adhaar', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('mlevel.bank1',),
        ),
    ]
